services:
  app:
    container_name: app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U  " ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  db_test:
    container_name: postgres_test
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    ports:
      - "5433:5432"

  migrate:
    container_name: migrate
    build: .
    depends_on:
      - db
      - app
    command: alembic upgrade head

volumes:
  db_data: